# Generated by Django 3.2.9 on 2021-11-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='articles',
            new_name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(default='draft', max_length=200, null=True),
        ),
    ]
